# Generated by Django 3.1.3 on 2020-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='random_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Рандомное поле'),
        ),
    ]
